2023-05-06 22:40:30,014 INFO    MainThread:84679 [wandb_setup.py:_flush():69] setting env: {}
2023-05-06 22:40:30,015 INFO    MainThread:84679 [wandb_setup.py:_flush():69] setting login settings: {}
2023-05-06 22:40:30,016 INFO    MainThread:84679 [wandb_init.py:_log_setup():357] Logging user logs to /gdrive/MyDrive/TransSeg/src/wandb/run-20230506_224029-b3a4jpj7/logs/debug.log
2023-05-06 22:40:30,016 INFO    MainThread:84679 [wandb_init.py:_log_setup():358] Logging internal logs to /gdrive/MyDrive/TransSeg/src/wandb/run-20230506_224029-b3a4jpj7/logs/debug-internal.log
2023-05-06 22:40:30,016 INFO    MainThread:84679 [wandb_init.py:init():390] calling init triggers
2023-05-06 22:40:30,017 INFO    MainThread:84679 [wandb_init.py:init():395] wandb.init called with sweep_config: {}
config: {'data_dir': 'data/msd/processed/Task06_Lung/', 'split_json': 'dataset_5slices.json', 'train_batch_size': 2, 'eval_batch_size': 2, 'clip_range': [-175, 250], 'mean_std': None, 'force_2d': 0, 'use_pretrained': 1, 'bootstrap_method': 'centering', 'in_channels': 1, 'out_channels': 14, 'patch_size': 16, 'img_size': [512, 512, 5], 'encoder': 'beit', 'decoder': 'upernet', 'loss_type': 'dicefocal', 'dropout_rate': 0.0, 'learning_rate': 3e-05, 'weight_decay': 0.05, 'warmup_steps': 20, 'max_steps': 25000, 'default_root_dir': '.', 'gpus': -1, 'val_check_interval': 1.0, 'check_val_every_n_epoch': 100, 'gradient_clip_val': 1.0, 'accumulate_grad_batches': 1, 'log_every_n_steps': 1, 'precision': 32, 'accelerator': 'ddp', 'seed': 1234, 'evaluation': 1, 'model_path': 'data/bcv/processed/checkpoint/ours/centering/epoch=10-step=12154.ckpt', 'checkpoint_dir': 'checkpoints'}
2023-05-06 22:40:30,017 INFO    MainThread:84679 [wandb_init.py:init():435] starting backend
2023-05-06 22:40:30,017 INFO    MainThread:84679 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-05-06 22:40:30,125 INFO    MainThread:84679 [backend.py:ensure_launched():135] starting backend process...
2023-05-06 22:40:30,231 INFO    MainThread:84679 [backend.py:ensure_launched():139] started backend process with pid: 85952
2023-05-06 22:40:30,234 INFO    MainThread:84679 [wandb_init.py:init():440] backend started and connected
2023-05-06 22:40:30,237 INFO    MainThread:84679 [wandb_init.py:init():499] updated telemetry
2023-05-06 22:40:30,238 INFO    MainThread:84679 [wandb_init.py:init():522] communicating current version
2023-05-06 22:40:31,268 INFO    MainThread:84679 [wandb_init.py:init():527] got version response upgrade_message: "wandb version 0.15.2 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2023-05-06 22:40:31,268 INFO    MainThread:84679 [wandb_init.py:init():535] communicating run to backend with 30 second timeout
2023-05-06 22:40:31,955 INFO    MainThread:84679 [wandb_init.py:init():562] starting run threads in backend
2023-05-06 22:40:36,617 INFO    MainThread:84679 [wandb_run.py:_console_start():1651] atexit reg
2023-05-06 22:40:36,619 INFO    MainThread:84679 [wandb_run.py:_redirect():1525] redirect: SettingsConsole.REDIRECT
2023-05-06 22:40:36,620 INFO    MainThread:84679 [wandb_run.py:_redirect():1530] Redirecting console.
2023-05-06 22:40:36,621 INFO    MainThread:84679 [wandb_run.py:_redirect():1586] Redirects installed.
2023-05-06 22:40:36,621 INFO    MainThread:84679 [wandb_init.py:init():587] run started, returning control to user process
2023-05-06 22:40:36,622 INFO    MainThread:84679 [wandb_run.py:_config_callback():878] config_cb None None {'force_2d': 0, 'use_pretrained': 1, 'bootstrap_method': 'centering', 'in_channels': 1, 'out_channels': 14, 'patch_size': 16, 'img_size': [512, 512, 5], 'hidden_size': 768, 'mlp_dim': 3072, 'num_heads': 12, 'num_layers': 12, 'encoder': 'beit', 'decoder': 'upernet', 'loss_type': 'dicefocal', 'save_preds': False, 'dropout_rate': 0.0, 'learning_rate': 3e-05, 'weight_decay': 0.05, 'warmup_steps': 20, 'max_steps': 25000, 'adam_epsilon': 1e-08}
2023-05-06 23:00:24,215 INFO    MainThread:84679 [wandb_run.py:_atexit_cleanup():1621] got exitcode: 255
2023-05-06 23:00:24,215 INFO    MainThread:84679 [wandb_run.py:_restore():1593] restore
2023-05-06 23:00:26,337 INFO    MainThread:84679 [wandb_run.py:_wait_for_finish():1746] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1310
  total_bytes: 1310
}

2023-05-06 23:00:26,682 INFO    MainThread:84679 [wandb_run.py:_wait_for_finish():1746] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1310
  total_bytes: 1310
}

2023-05-06 23:00:26,683 INFO    MainThread:84679 [wandb_run.py:_restore():1593] restore
2023-05-06 23:00:29,297 ERROR   MainThread:84679 [wandb_run.py:_atexit_cleanup():1639] Problem finishing run
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1629, in _atexit_cleanup
    self._on_finish()
  File "/usr/local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1805, in _on_finish
    self._poll_exit_response = self._wait_for_finish()
  File "/usr/local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1752, in _wait_for_finish
    self._on_finish_progress(pusher_stats, done)
  File "/usr/local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1740, in _on_finish_progress
    self._pusher_print_status(progress, done=done)
  File "/usr/local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1722, in _pusher_print_status
    wandb.termlog(line, newline=False, prefix=prefix)
  File "/usr/local/lib/python3.8/site-packages/wandb/errors/term.py", line 36, in termlog
    _log(
  File "/usr/local/lib/python3.8/site-packages/wandb/errors/term.py", line 94, in _log
    click.echo(line, file=sys.stderr, nl=newline)
  File "/usr/local/lib/python3.8/site-packages/click/utils.py", line 298, in echo
    file.write(out)  # type: ignore
OSError: [Errno 5] Input/output error
